### PR TITLE
Add ssl capabilities

### PR DESCRIPTION
**Pull request by stellarxo**
Adds the following configuration options:
```
kafka.ssl.ca_cert
kafka.ssl.client_cert
kafka.ssl.client_cert_key
```
(Also fixed some misc typos)

Please let me know if I'm missing anything!

@mensfeld @jpcaissy

### CODE REVIEW

**Comment by mensfeld** [comment]
Hello @stellarxo  thank you for this awesome feature! I will review it in 2 days and get back to you. Great job!

**Comment by mensfeld** [comment]
@stellarxo  awesome! I will merge it, dump ruby-kafka na release a new version. Thank you!

**Comment by jens** [comment]
Any plans on making a new gem release with this included?

**Comment by mensfeld** [comment]
Yes. Max in 1 week.

**Comment by jens** [comment]
Great. Thanks :-)

**Comment by mensfeld** [comment]
@jens it should be released this week. Once @mach_kernel fixes some stylings and I can merge #27  it will be released.

**Comment by mensfeld** [comment]
@jens here you go: https://rubygems.org/gems/waterdrop/versions/0.3.2.4

**Pull request merged**
