### PR TITLE
Add delegate requirement

### PR DESCRIPTION
**Pull request by samsm**
This seems to be needed now but I have tracked down _why_ yet.

### CODE REVIEW

**Comment by mensfeld** [comment]
Oooo this is weird... though it may be that it's being included in activesupport that's why I did not. Let me fix this and issue another release fast.

**Comment by mensfeld** [comment]
Hmmm :thinking: it works even when no external gems are used on my side. Can you provide me with some repro? :pray:

**Comment by mensfeld** [comment]
Ok I have it.

**Review by mensfeld — APPROVED** [review]

**Comment by mensfeld** [comment]
waterdrop (2.7.2) released

**Comment by mensfeld** [comment]
@samsm integration to ensure this and similar do not happen ever again: https://github.com/karafka/karafka/pull/2091

**Comment by samsm** [comment]
Thanks! I had a similar experience where I was having trouble determining the conditions where this happens, appreciate you tracking it down 😅

**Comment by mensfeld** [comment]
No problem. It was challenging because this would not occur with rails or even karafka loaded. Also could occur depending on load order and other factors. Fixed and released. Enjoy :pray:

**Pull request merged**
